/*******************************************************************************************************/
/* WROVER + ILI9341(VSPI) + I2S + SD(VSPI) + Encoder1. Maleksm МОД + батарейка + Mute. Делитель (38.6х100.0) - 36-й пин. */
/********************************************************************************************************/
/* Generated by ёRadio - simple myoptions.h generator - v0.9.0
https://trip5.github.io/ehRadio_myoptions/generator.html?b=ESP32-DevKit-V1_38Pin&r=72,1,2,4,6,7,9,19,41,43,54,64,67,68&i=1,2,3,4,15,16,17,28,29,30,39,41,42&v=4,5,-1,15,27,26,25,35,34,39,22,21,2 
Put this file next to yoRadio.ino and restart Arduino IDE. */

#ifndef myoptions_h
#define myoptions_h

//#define LED_BUILTIN  2                 /*  Onboard LED Pin */
//#define LED_INVERT      false             /*  Invert Onboard LED? */
//#define DSP_INVERT_TITLE  false            /*  Инверсные цвета названия станции (заголовок дисплея). По умолчанию "true"  */
//#define EXT_WEATHER       true            /*  Расширенная погода. По умолчанию "true"  */
//#define CLOCKFONT_MONO    false           /* Откл/Вкл моношрифтов для часов TFT дисплеев. По умолчанию "true"  */
//#define RSSI_DIGIT        true            /* Графический/цифровой значок Wi-Fi. (false - лесенка (по умолчанию), true - цифирьки) */
//#define BITRATE_FULL      false            /* Значек битрейта. По умолчанию "true" */ 
#define L10N_LANGUAGE RU      /*  Language (EN, RU). More info in yoRadio/locale/displayL10n_(en|ru).h*/
/******************************************/

/* Display */
//#define DSP_MODEL    DSP_ST7735  /* Select ST7735*/
//#define DTYPE     INITR_GREENTAB  /*  ST7735 display submodel. По умолчанию "INITR_BLACKTAB" */
#define DSP_MODEL    DSP_ILI9341 /* Select ILI9341*/
//#define DSP_MODEL   DSP_ST7789  /* Select ST7789*/
//#define DSP_MODEL   DSP_ST7789_170  /* Select ST7789x170*/
//#define DSP_MODEL    DSP_SSD1306x32    /* Select SSD1306-128х32*/
//#define DSP_MODEL    DSP_SH1106    /* Select SH1106-128х64*/
/* **************************************** */

/*  I2C PINS  */
//#define I2C_SDA           23                /*  I2C SDA pin. It is best to connect to pin 21.  */
//#define I2C_SCL           18                /*  I2C SCL pin. It is best to connect to pin 22.  */
//#define I2C_RST           -1                /*  I2C RST pin. Set to -1 if not used  */

/* TFT VSPI PINS. SCL(SCK, CLK) must be connected to pin 18
               SDA(MOSI, DIN, SDI) must be connected to pin 23 */
#define TFT_CS            5    /*  SPI CS pin  */
#define TFT_RST          -1    /*  SPI RST pin.  set to -1 and connect to Esp EN pin */
#define TFT_DC            4    /*  SPI A0/DC/RS pin  */
#define BRIGHTNESS_PIN    15    /*  Pin LED for adjusting the brightness of the display (output 0 - 3v3) */
/*  TFT HSPI PINS. SCL(SCK, CLK) must be connected to pin 14
                    SDA(MOSI, DIN, SDI) must be connected to pin 13  */
//#define DSP_HSPI  true    /*  Use HSPI for display. По умолчанию "false"  */
/* **************************************** */

/*  I2S DAC    */
#define I2S_DOUT    27   /*  DIN connection. Should be set to 255 if the board is not used */
#define I2S_BCLK     26   /*  BCLK Bit clock */
#define I2S_LRC       25  /*  WSEL Left Right Clock */
//#define I2S_MCLK      32    /*  MCLK - Master Clock . МОД Maleksm (с версии v0.9.535(m)-3.4.2p) */
/******************************************/

/*  VS1053 PINS. VS1053 SCK must be connected to pin 18
                 VS1053 MISO must be connected to pin 19
                 VS1053 MOSI must be connected to pin 23  */
#define VS1053_CS     255    /*  XCS pin. Should be set to 255 if the board is not used */
//#define VS1053_DCS    25    /*  XDCS pin.  */
//#define VS1053_DREQ   26    /*  DREQ pin.  */
//#define VS1053_RST    -1    /*  XRESET pin. Set to -1 if connected to Esp EN pin */
/*  VS1053 HSPI PINS. VS1053 SCK must be connected to pin 14
                      VS1053 MISO must be connected to pin 12 (+10 KOm на GND)
                      VS1053 MOSI must be connected to pin 13  */
//#define VS_HSPI   false   /*  Use HSPI for VS. По умолчанию "false" */
/******************************************/

/*  BUTTONS  */
//#define BTN_LEFT      33    /*  VolDown, Prev */
//#define BTN_CENTER    32    /*  Play, Stop, Show playlist */
//#define BTN_RIGHT     22    /*  VolUp, Next */
//#define BTN_UP      255   /*  Prev, Move Up */
//#define BTN_DOWN    255   /*  Next, Move Down */
#define BTN_INTERNALPULLUP    false    /*  Enable the weak pull up resistors. По умолчанию "true" */
//#define BTN_LONGPRESS_LOOP_DELAY  200   /*  Delay between calling DuringLongPress event . По умолчанию "200" */
//#define BTN_CLICK_TICKS     300   /*  Event Timing https://github.com/mathertel/OneButton#event-timing По умолчанию "300" */
//#define BTN_PRESS_TICKS     500   /*  Event Timing https://github.com/mathertel/OneButton#event-timing По умолчанию "500" */
/******************************************/

/*  ENCODERs  */
#define ENC_BTNL              35       /*  Левое вращение энкодера (S1, DT)*/
#define ENC_BTNR              34       /*  Правое вращение энкодера (S2, CLK) */
#define ENC_BTNB              39       /*  Кнопка энкодера (Key, SW))*/
//#define ENC2_BTNL             35       /*  Левое вращение энкодера-2 (S1, DT)*/
//#define ENC2_BTNR             34       /*  Правое вращение энкодера-2 (S2, CLK) */
//#define ENC2_BTNB             39       /*  Кнопка энкодера-2 (Key, SW))*/
#define ENC_INTERNALPULLUP    false    /*  Enable the weak pull up resistors. По умолчанию "true"  */
#define ENC2_INTERNALPULLUP   false    /*  Enable the weak pull up resistors. По умолчанию "true"  */
/* **************************************** */

/*  SDCARD  */
/*  MISO is the same as D0, MOSI is the same as D1 */
/*  SD VSPI PINS. SD SCK must be connected to pin 18
                  SD MISO must be connected to pin 19
                  SD MOSI must be connected to pin 23  */
/*  SD HSPI PINS. SD SCK must be connected to pin 14
                  SD MISO must be connected to pin 12     (+20 KOm на GND или через 10 mF)
                  SD MOSI must be connected to pin 13  */
#define SDC_CS        22        /* SDCARD CS pin */
//#define SD_SPIPINS  18, 19, 23      /* SCK, MISO, MOSI */
//#define SD_HSPI     true      /* use HSPI for SD (miso=12, mosi=13, clk=14) instead of VSPI (by default)  */
/* **************************************** */

/*  Other settings.  */

#define MUTE_PIN    2   /*  MUTE Pin  (Pin2 - можно совместно использовать с диодом на devboard) */
#define MUTE_VAL    LOW   /*  Write this to MUTE_PIN when player is stopped. (HIGH or LOW) По умолчанию "HIGH" */
//#define PLAYER_FORCE_MONO false  /*  mono option on boot - false stereo, true mono. По умолчанию "false" */
//#define I2S_INTERNAL    false    /*  If true - use esp32 internal DAC. По умолчанию "false" */
//#define ROTATE_90   false   /*  Optional 90 degree rotation for square displays. По умолчанию "false"*/
//#define TFT_ROTATE      0   /*  Display rotation. 0 - 0, 1 - 90, 2 - 180, 3 - 270 degrees */
//#define HIDE_VOLPAGE             /* Скрыть страницу "Громкость", ориентируемся по прогрессбару громкости. (МОД nva_lw)  */
//#define HIDE_DATE       /* Скрыть дату. (МОД nva_lw и Maleksm)  */
//#define BOOMBOX_STYLE     /* Разные варианты "показометра" VUmetr. Столбик, если строку закоментировать. */
//#define WAKE_PIN              255
//#define NAME_STRIM              /* Показывать имя станции из стрима. (МОД Maleksm)  */

//#define DOWN_LEVEL           2      /* минимальный уровень подсветки (от 0 до 255) По умолчанию "2". (МОД Maleksm) */
//#define DOWN_INTERVAL        60     /* интервал для BacklightDown в сек (60 сек = 1 мин) По умолчанию "60". (МОД Maleksm) */
/* ***************************************** */

/*  Аккумулятор */
//#define BATTERY_OFF           /* Скрыть показатель уровня заряда и напряжения аккумулятора */
//#define HIDE_VOLT               /* Скрыть только показатель напряжения аккумулятора */
//#define ADC_PIN          36      /* Пин 36 (или 39) для считывания с делителя напряжения аккумулятора. По умолчанию 36. */
#define R1               38.6     /* Номинал резистора, подключенного к плюсу батареи, в КОм или Ом. По умолчанию 50. */
#define R2               100.0     /* Номинал резистора, подключенного к минусу, в КОм  или Ом. По умолчанию 100. */
#define DELTA_BAT       -0.002    /* Величина коррекции показаний напряжения батареи в вольтах */
/* *************** ************************ */
#define GRND_HEIGHT      231     /* (231 м) Высота местности над уровнем моря в метрах для поправки в давление */

/*  Indicator TM1637           МОД Maleksm (с версии v0.9.435(m)-3.3.2a) */
//#define TM_CLK       32    /* GPIO для CLK. Для TM1637 обязательный параметр. */
//#define TM_DIO       33    /* GPIO для DIO. Для TM1637 обязательный параметр. */
//#define TM_BRIGHT    5    /* Яркость индикатора TM1637. Необязательный параметр. Допустимые значения 0 - 7. По умолчанию 4. */
/* **************************************** */

/*  IR control  */
//#define IR_PIN                21
//#define IR_TIMEOUT        80              /*  see kTimeout description in IRremoteESP8266 example */
                   /*  https://github.com/crankyoldgit/IRremoteESP8266/blob/master/examples/IRrecvDumpV2/IRrecvDumpV2.ino */
/******************************************/

/*  RTC control  */
//#define RTC_MODULE    DS3231  /* или DS1307  */
//#define RTC_SDA       255    /* 14 */
//#define RTC_SCL       255    /* 13 */
/* **************************************** */

#endif
